import {createRequire} from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const out=process.env.EG2_QA_OUT||'/tmp/eg2-arena-qa';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:process.env.QA_HEADED!=='1',channel:'chrome',args:['--use-angle=metal','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});page.on('response',r=>{if(r.status()>=400)failed.push({url:r.url(),status:r.status()});});
try{
 await page.goto('http://127.0.0.1:8766/');await page.waitForFunction(()=>window.EG2Arena?.ready,{timeout:60000});
 await page.screenshot({path:path.join(out,'01-arena.png')});
 const init=await page.evaluate(()=>({renderer:EG2Arena.renderer,drawInfo:EG2Arena.drawInfo,origin:EG2Arena.origin}));
 await page.getByRole('button',{name:'Enviar agente',exact:true}).click();
 const full=await page.evaluate(()=>{
  // Observe completion under the decoded walk speed; don't tune speed to a deadline.
  for(let i=0;i<120&&!EG2Arena.snapshot().agents[0]?.finished;i++)EG2Arena.advance(.25);
  return EG2Arena.snapshot();
 });
 const historyHUD=await page.locator('#chain-result').textContent();
 await page.screenshot({path:path.join(out,'02-history-with-recovery.png')});
 await page.getByRole('button',{name:'Reiniciar teste',exact:true}).click();
 await page.getByRole('button',{name:'Luva',exact:true}).click();
 await page.getByLabel('Alimentação ligada').uncheck();
 await page.getByRole('button',{name:'Enviar agente',exact:true}).click();
 const disabled=await page.evaluate(()=>EG2Arena.advance(18));
 await page.getByRole('button',{name:'Montagem inicial',exact:true}).click();
 await page.getByRole('button',{name:'Bolha',exact:true}).click();
 await page.getByRole('button',{name:'Girar ↻',exact:true}).click();
 await page.getByRole('button',{name:'Girar ↻',exact:true}).click();
 await page.getByRole('button',{name:'Girar ↻',exact:true}).click();
 await page.getByRole('button',{name:'Girar ↻',exact:true}).click();
 await page.getByRole('button',{name:'Enviar agente',exact:true}).click();
 const rotated=await page.evaluate(()=>EG2Arena.advance(18));
 await page.getByRole('button',{name:'Montagem inicial',exact:true}).click();
 await page.getByRole('button',{name:'Pausar',exact:true}).click();
 const before=await page.evaluate(()=>EG2Arena.snapshot().time);await page.waitForTimeout(200);
 const after=await page.evaluate(()=>EG2Arena.snapshot().time);
 await page.getByRole('button',{name:'Continuar',exact:true}).click();
 await page.getByRole('button',{name:'Iniciar onda · 6',exact:true}).click();
 const wave=await page.evaluate(()=>EG2Arena.advance(40));
 await page.getByRole('button',{name:'Som desligado',exact:true}).click();
 await page.waitForFunction(()=>EG2Arena.audio.decoded.length===6,{timeout:30000});
 const audio=await page.evaluate(()=>EG2Arena.audio);
 await page.getByRole('button',{name:'Salvar montagem',exact:true}).click();
 await page.getByRole('button',{name:'Bolha',exact:true}).click();
 await page.getByRole('button',{name:'Reposicionar',exact:true}).click();
 const oldPosition=await page.evaluate(()=>EG2Arena.snapshot().traps[2]);
 await page.locator('#viewport canvas').click({position:{x:680,y:490}});
 const newPosition=await page.evaluate(()=>EG2Arena.snapshot().traps[2]);
 await page.locator('#scenario').selectOption('open');
 await page.getByRole('button',{name:'Salvar montagem',exact:true}).click();
 const saved=await page.evaluate(()=>localStorage.getItem('eg2-trap-arena-layout-v1'));
 await page.reload();await page.waitForFunction(()=>window.EG2Arena?.ready);
 const restored=await page.evaluate(()=>EG2Arena.snapshot().traps);
 await page.evaluate(()=>{for(let i=0;i<6;i++)EG2Arena.spawn();});
 const timing=await page.evaluate(async()=>{let previous=performance.now();const frames=[];for(let i=0;i<60;i++){await new Promise(requestAnimationFrame);const now=performance.now();frames.push(now-previous);previous=now;}return {activeAgents:EG2Arena.snapshot().agents.filter(a=>a.alive).length,samples:frames.length,medianMs:frames.sort((a,b)=>a-b)[30],p95Ms:frames[57]};});
 const result={schema:2,scope:'Reconstructed controls and contact/episode bookkeeping; original physics and a continuous five-device chain remain unverified',init,full,historyHUD,disabled,rotated,pause:{before,after},wave,audio,saved,restored,oldPosition,newPosition,timing,errors,failed};
 const checks={history:full.agents[0].hits.join(',')==='fan,glove,bubble,slip,laser',continuity:full.chains===0&&full.agents[0].episodes.length===2&&historyHUD.includes('no histórico')&&!historyHUD.includes('Cadeia completa'),disabled:disabled.chains===0&&!disabled.agents[0].hits.includes('glove'),rotated:rotated.chains===0&&!rotated.agents[0].hits.includes('bubble'),pause:before===after,wave:wave.chains===0&&wave.kills===6,audio:audio.decoded.length===6,placement:oldPosition.x!==newPosition.x||oldPosition.z!==newPosition.z,saved:JSON.parse(saved).layout[2].x===restored[2].x&&JSON.parse(saved).layout[2].z===restored[2].z,scenario:await page.locator('#scenario').inputValue()==='open',noErrors:errors.length===0&&failed.length===0};
 result.checks=checks;fs.writeFileSync(path.join(out,'qa.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({out,checks,renderer:init.renderer,timing,errors,failed}));
 if(Object.values(checks).some(v=>!v))process.exitCode=1;
}finally{await browser.close();}
